### ISSUE TITLE
Why not host it as Github page ?

### ISSUE THREAD

**Issue by rubenCodeforges** [greeze/ZomboidChecklist#3]

**Comment by VeinsOfSorrow** [comment]
Hello @rubenCodeforges, I have taken this project over with permission from the owner. I am going to see if I can host it as a GitHub page and I will let you know how it works. Great idea +1

**Comment by VeinsOfSorrow** [comment]
@rubenCodeforges it's being hosted here: https://thecryptek.github.io/ZomboidChecklist/
